name: docs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    name: "Build and deploy documentation"
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
        if: ${{github.ref != 'refs/heads/main'}}
      - uses: "actions/checkout@v3"
      - name: Set up Python 3.11
        uses: "actions/setup-python@v4"
        with:
            python-version: 3.11
            cache: 'pip'
      - name: Install dependencies
        run: |
          set -xe
          pip install --upgrade pip setuptools wheel
          pip install -r docs/requirements.txt
      - name: Build documentation
        run: |
          set -xe
          python -VV
          cd docs && make clean && make html

      - uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '_build/html'
          destination-github-username: 'fabianp'
          destination-repository-name: 'jaxopt.github.io'
          user-email: jaxopt@google.com
          target-branch: main
          target-directory: dev
